### ISSUE TITLE
Minor issue: Unhelpful error when trying to download db into non-existing directory.

### ISSUE THREAD

**Issue by dspeth** [grp-bork/gunc#1]
Minor issue: 
Unhelpful error when trying to download db into non-existing directory.

Explanation:
There is no consistency amongst bioinformatics software whether a target directory has to or is not allowed to exist prior to running the command. In the case of "gunc download_db" the target dir needs to be created in advance, but the error isn't particularly helpful.

version:
version 1.0.0 through bioconda on a linux system

Command run
gunc download_db /export/data1/db/GUNC

Result:
[START] 15:09:44 2020-12-17
[INFO] DB downloading...
Traceback (most recent call last):
  File "/export/data1/sw/anaconda3-2019.07/envs/dRep/bin/gunc", line 10, in <module>
    sys.exit(main())
  File "/export/data1/sw/anaconda3-2019.07/envs/dRep/lib/python3.6/site-packages/gunc/gunc.py", line 507, in main
    gunc_database.get_db(args.path)
  File "/export/data1/sw/anaconda3-2019.07/envs/dRep/lib/python3.6/site-packages/gunc/gunc_database.py", line 101, in get_db
    download_file(gz_file_url, gz_file_path)
  File "/export/data1/sw/anaconda3-2019.07/envs/dRep/lib/python3.6/site-packages/gunc/gunc_database.py", line 39, in download_file
    with open(out_file, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/export/data1/db/GUNC/gunc_db_2.0.4.dmnd.gz'

**Comment by fullama** [comment]
Fair point.. ill add a more helpful error message.. thanks!

**Comment by fullama** [comment]
`gunc v1.0.1` has been released with a better error message.

..any other suggestions - keep them coming!
