### ISSUE TITLE
Cant download the database

### ISSUE THREAD

**Issue by thh32** [grp-bork/gunc#13]
We are using conda 4.7.5 and when installing v1.0.3 of GUNC, the 

```
(gunc)$ gunc download_db ./
[START] 09:36:08 2021-07-16
[INFO] DB downloading...
Traceback (most recent call last):
  File "/home/ecoli/anaconda/envs/gunc/bin/gunc", line 10, in <module>
    sys.exit(main())
  File "/home/ecoli/anaconda/envs/gunc/lib/python3.6/site-packages/gunc/gunc.py", line 561, in main
    gunc_database.get_db(args.path, args.database)
  File "/home/ecoli/anaconda/envs/gunc/lib/python3.6/site-packages/gunc/gunc_database.py", line 108, in get_db
    download_file(gz_file_url, gz_file_path)
  File "/home/ecoli/anaconda/envs/gunc/lib/python3.6/site-packages/gunc/gunc_database.py", line 38, in download_file
    with requests.get(file_url, stream=True) as r:
AttributeError: __enter__
```

Seeing other peoples problems I tried downgrading to version 1.0.1, but got the same error;
```
(gunc)$ gunc download_db ./
[START] 09:39:26 2021-07-16
[INFO] DB downloading...
Traceback (most recent call last):
  File "/home/ecoli/anaconda/envs/gunc/bin/gunc", line 10, in <module>
    sys.exit(main())
  File "/home/ecoli/anaconda/envs/gunc/lib/python3.6/site-packages/gunc/gunc.py", line 520, in main
    gunc_database.get_db(args.path)
  File "/home/ecoli/anaconda/envs/gunc/lib/python3.6/site-packages/gunc/gunc_database.py", line 104, in get_db
    download_file(gz_file_url, gz_file_path)
  File "/home/ecoli/anaconda/envs/gunc/lib/python3.6/site-packages/gunc/gunc_database.py", line 38, in download_file
    with requests.get(file_url, stream=True) as r:
AttributeError: __enter__
```
Is there any solution to this?

**Comment by fullama** [comment]
What version of requests are you using? maybe you could try upgrading it and see if that solves the problem?

**Comment by fullama** [comment]
I added the requirement for correct requests version in the latest version of gunc 1.0.4.. you could try upgrading gunc and see if that fixes your issue..

**Comment by fullama** [comment]
This issue was closed due to inactivity. Please reach out if you have or find the answers we need so that we can investigate further.
