### ISSUE TITLE
Failed to run Diamond

### ISSUE THREAD

**Issue by ahmedmagds** [grp-bork/gunc#31]
I keep getting this error "Failed to run Diamond gunc_out/gene_calls/merged.genecalls.faa"
`gunc run -r gunc_db_progenomes2.1.dmnd -i genome4.fna -o gunc_out -e .fna`
When I check the gene_calls folder, I find genome4.genecalls.faa. Is this the issue that the program cannot find merged.....?

**Comment by fullama** [comment]
unfortunately the error message is not so informative (this will be fixed in the next version)
would you like to send me the input file and i can look to see why diamond fails?

**Comment by ahmedmagds** [comment]
[genome4.fna.txt.zip](https://github.com/grp-bork/gunc/files/10921939/genome4.fna.txt.zip)
Sure, thanks for help!

**Comment by ahmedmagds** [comment]
@fullama It does seem installation issue. I tried to install it on our cluster and I also get this error.
`gunc -h
Traceback (most recent call last):
  File "/home/ahmed/miniconda3/envs/gunc/bin/gunc", line 6, in <module>
    from gunc.gunc import main
  File "/home/ahmed/miniconda3/envs/gunc/lib/python3.6/site-packages/gunc/gunc.py", line 14, in <module>
    from . import visualisation as vis
  File "/home/ahmed/miniconda3/envs/gunc/lib/python3.6/site-packages/gunc/visualisation.py", line 4, in <module>
    import plotly.graph_objects
  File "/home/ahmed/miniconda3/envs/gunc/lib/python3.6/site-packages/plotly/__init__.py", line 35, in <module>
    from plotly import (
  File "/home/ahmed/miniconda3/envs/gunc/lib/python3.6/site-packages/plotly/io/__init__.py", line 12, in <module>
    from ._renderers import renderers, show
  File "/home/ahmed/miniconda3/envs/gunc/lib/python3.6/site-packages/plotly/io/_renderers.py", line 7, in <module>
    from packaging.version import Version
ModuleNotFoundError: No module named 'packaging'`
I also got this error when I tried to install it on my Mac M1. I solved this issue by updating python. I am not sure though is this caused problems downstream for diamond. I installed gunc using `mamba create -n gunc -c bioconda gunc`. . For some reason it installed gun 1.0.3 so I needed to update  it using `mamba update gunc`. Let me know your thoughts and I appreciate your help.
