### ISSUE TITLE
Command 'diamond --version' returned non-zero exit status 132

### ISSUE THREAD

**Issue by sigau** [grp-bork/gunc#34]
Hi,
I have install gunc with conda. 

When I run gunc with the command : 
gunc run -i /beegfs/project/nega/assembly/re-run-article/hifiasm_pacbio/hifiasm/assembly_coiffaiti_hifiasm.asm.bp.p_ctg.fa -r /beegfs/data/gdebaecker/soft/gunc_db/gunc_db_progenomes2.1.dmnd -t 16

I got the following error : 

'''
Illegal instruction
Traceback (most recent call last):
  File "/beegfs/data/gdebaecker/myconda/conda-env/gunc/bin/gunc", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/beegfs/data/gdebaecker/myconda/conda-env/gunc/lib/python3.11/site-packages/gunc/gunc.py", line 712, in main
    start_checks()
  File "/beegfs/data/gdebaecker/myconda/conda-env/gunc/lib/python3.11/site-packages/gunc/gunc.py", line 228, in start_checks
    diamond_ver = external_tools.check_diamond_version()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/beegfs/data/gdebaecker/myconda/conda-env/gunc/lib/python3.11/site-packages/gunc/external_tools.py", line 169, in check_diamond_version
    subprocess.check_output(
  File "/beegfs/data/gdebaecker/myconda/conda-env/gunc/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/beegfs/data/gdebaecker/myconda/conda-env/gunc/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'diamond --version' returned non-zero exit status 132.
''''

but when I try the command : diamond --version --> diamond version 2.0.4 

Do you know how I can correct this ? 

Thanks in advance,
Gautier

**Comment by fullama** [comment]
Hmm that's a new one.. could you post the output of 'conda list' ?

**Comment by sigau** [comment]
here is it : 
[conda_list_gunc.txt](https://github.com/grp-bork/gunc/files/11332450/conda_list_gunc.txt)

**Comment by fullama** [comment]
are you running on the same system where you installed gunc/diamond? and the same as where you ran `diamond --version `?
