### ISSUE TITLE
Low quality/low gene numbers faa input causes crash

### ISSUE THREAD

**Issue by cschu** [grp-bork/gunc#46]
Hi, 

running `gunc` with low quality, low gene numbers peptide sequence input can cause a crash in one of the called pandas functions. So far this has happened with 6 different input files. One of them is included here.

Command line used: `gunc run -i input.faa -e .faa -v -g -t 8 --detailed_output`

input used: [input.faa.txt](https://github.com/user-attachments/files/17043540/input.faa.txt)

Version used: `quay.io/biocontainers/gunc:1.0.5--pyhdfd78af_0`

Error message from the log:

```
[...]
00:24:47 : [   INFO] : gunc.py:534             run_gunc() : START Scoring
00:24:47 : [   INFO] : gunc.py:569             run_gunc() : END   Scoring
Traceback (most recent call last):
  File "/usr/local/bin/gunc", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gunc/gunc.py", line 876, in main
    run(args)
  File "/usr/local/lib/python3.12/site-packages/gunc/gunc.py", line 697, in run
    gunc_output = run_gunc(
                  ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gunc/gunc.py", line 570, in run_gunc
    return pd.concat(gunc_output).sort_values("genome")
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 380, in concat
    op = _Concatenator(
         ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 443, in __init__
    objs, keys = self._clean_keys_and_objs(objs, keys)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 505, in _clean_keys_and_objs
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
```

Thanks,
Christian

**Comment by fullama** [comment]
This is fixed in the next gunc version that will be released soon!
